services:
  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/:/etc/nginx/certs/
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true