services:
  nginx_proxy:
    build: ./nginx
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/:/etc/nginx/certs/
    networks:
      - proxy-network

  dyndns:
    build: ./dynamic-dns
    container_name: dyndns
    restart: unless-stopped

networks:
  proxy-network:
    external: true